name: Build/Test/Deploy
on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:

jobs:
  build-lint:
    uses: dortania/shared-tooling/.github/workflows/build-guide.yml@main
    secrets: inherit
